### ISSUE TITLE
Support json config format

### ISSUE THREAD

**Issue by nicolas63** [jhipster/consul-config-loader#27]
the blueprint dotnet has a json configuration instead of yml do you think it's possible to support this format ? If it's ok for you I can do the PR

**Comment by pascalgrimaud** [comment]
@nicolas63 : if you know how to do it, plz go ahead
Don't forget yml should be the default :)

**Comment by nicolas63** [comment]
Sorry, the script already have this possiblity with CONFIG_FORMAT (https://github.com/jhipster/consul-config-loader/blob/main/load-config.sh#L11)
